on:
  # push할 때마다 액션 실행하게 하려면 # 제거
  #push:
  #branches:
  #-develop

  workflow_dispatch: # 수동 실행 설정, 깃허브 액션 페이지에서 클릭으로 실행 가능
    inputs:
      component:
        description: "What component"
        required: true
        default: "web-dev"
      profile:
        description: "What profile"
        required: true
        default: "deploy-dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: echo ${{ GITHUB_RUN_ID }}
